#!/usr/bin/env bash
# Combine GrandMaster-brief answer sections into one Markdown file and optionally PDF.
# Usage (from repo root Prep/):
#   ./scripts/export-pdf.sh
#   OUT=/path/to/out.pdf ./scripts/export-pdf.sh
#
# PDF requires Pandoc and a LaTeX engine (e.g. MacTeX) or wkhtmltopdf.
# Markdown-only (always works):
#   ONLY_MD=1 ./scripts/export-pdf.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$ROOT/docs/android-interview-2026"
ANS="$DOCS/answers"
BUILD="$ROOT/build"
COMBINED_MD="${COMBINED_MD:-$BUILD/android-interview-2026-combined.md}"
OUT="${OUT:-$BUILD/android-interview-2026-notes.pdf}"

mkdir -p "$BUILD"

ORDER=(
  "01-sdk-platform.md"
  "02-jetpack-libraries.md"
  "03-compose.md"
  "04-kotlin.md"
  "05-coroutines-flow.md"
  "06-database-storage.md"
  "07-build-gradle.md"
  "08-security.md"
  "09-devops-cicd.md"
  "10-architecture.md"
  "11-system-design.md"
  "12-testing.md"
  "13-performance.md"
  "14-misc-leadership.md"
)

{
  echo "# Android Interview 2026 — combined answers"
  echo ""
  echo "_Generated by scripts/export-pdf.sh — edit section files under docs/android-interview-2026/answers/_"
  echo ""
} >"$COMBINED_MD"

for f in "${ORDER[@]}"; do
  if [[ -f "$ANS/$f" ]]; then
    echo "" >>"$COMBINED_MD"
    cat "$ANS/$f" >>"$COMBINED_MD"
    echo "" >>"$COMBINED_MD"
    echo '---' >>"$COMBINED_MD"
  else
    echo "warn: missing $ANS/$f" >&2
  fi
done

echo "Wrote: $COMBINED_MD"

if [[ "${ONLY_MD:-0}" == "1" ]]; then
  echo "ONLY_MD=1 set; skipping PDF. Open the combined Markdown and use Print → Save as PDF if needed."
  exit 0
fi

if ! command -v pandoc >/dev/null 2>&1; then
  echo "Pandoc not found. Install: https://pandoc.org/installing.html"
  echo "Then re-run this script, or open $COMBINED_MD in an editor and Print to PDF."
  exit 0
fi

PDF_ENGINE_ARGS=()
if command -v xelatex >/dev/null 2>&1; then
  PDF_ENGINE_ARGS=(--pdf-engine=xelatex)
elif command -v pdflatex >/dev/null 2>&1; then
  PDF_ENGINE_ARGS=(--pdf-engine=pdflatex)
else
  echo "No xelatex/pdflatex found; Pandoc cannot emit PDF without a LaTeX install."
  echo "Combined Markdown is ready at: $COMBINED_MD"
  exit 0
fi

pandoc "${PDF_ENGINE_ARGS[@]}" "$COMBINED_MD" -o "$OUT"
echo "Wrote PDF: $OUT"
